### PR TITLE
🐛 Fix status board 

### LINKED ISSUE #129: 🐛 Fix status board
## Description:
With #119 the status board is now broken. This issues is about to fix it.

### 🟢 In scope:
* tbd
 
### 🔴 Not in scope:
* tbd

### PR DESCRIPTION
**Pull request by tjarbo**
This PR closes #129, because since the update of buefy, the board did not work. I remove any information about the discord bot and replaced it with three statistics about the connector service. The only problem is that the translation are not working correctly as the table will not be re-rendered if the language changes. But this is a low prio bug. 

### Screenshots
grafik

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

- ~[ ] Make sure you are requesting to main. Don't request to release branch!~
- [X] I have linked the related issue.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by p-fruck — APPROVED** [review]

File: packages/frontend/src/components/TheStatusBoard.vue [hunk 1]
```diff
@@ -41,11 +39,93 @@
...
+        { key: this.keys.connectorsActiveLength, value: connectorsActiveLength },
+        { key: this.keys.connectorsDefaultLength, value: connectorsDefaultLength },
+      ];
+    },
+    ...mapGetters(['statusBoardGetStatus', 'statusBoardGetData', 'fetchGetStatus']),
+  },
+  data() {
+    return {
+    // Column titles
+      columns: [
```
Comment (piuswalter) [inline packages/frontend/src/components/TheStatusBoard.vue:107]:
```suggestion
    return {
      // Column titles
      columns: [
```

**Review by piuswalter — CHANGES_REQUESTED** [review]

**Review by piuswalter — APPROVED** [review]
